name: Endor Labs - JavaScript SCA Scan on PR

on:
  workflow_dispatch:

jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
        
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 22
            cache: 'npm'
            cache-dependency-path: package-lock.json
          
        - name: Build Dependencies
          run: npm ci
          
        - name: Endor Labs SCA Scan
          uses: endorlabs/github-action@main
          with:
            namespace: "arsalan-learn"
            api: "https://api.endorlabs.com"
            enable_github_action_token: true
            scan_dependencies: true
            pr: true
            pr_baseline: main # develop, etc
            additional_args: "--pr-incremental --phantom-dependencies=true" # Additional parameters can be passed with whitespace separation, for example: --github to enable RSPM
            enable_pr_comments: true <-- Uncomment to enable PR comments if enabled comment out pr_baseline
            # scan_summary_output_type: "table" <-- Uncomment to choose the format, default it table
            github_token: ${{ secrets.GH_TOKEN }} # needs to be enabled if you want to use enable_pr_comments